# -*- coding: utf-8 -*-
"""Colab 시작하기의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQlhJ1kNaJ8PU9D0lkfTKK16qlLSMjXa

# 새 섹션
"""

!pip install -q streamlit plotly
!npm install -q localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# import matplotlib.pyplot as plt
# 
# # 페이지 설정
# st.set_page_config(page_title="전자기학 공학용 가이드", page_icon="📐", layout="wide")
# 
# # 상수 정의
# EPS_0 = 8.854e-12
# 
# # 앱 타이틀
# st.title("⚡ 전자기학 공식 마스터 & 공학 계산기")
# st.markdown("---")
# 
# # 사이드바 메뉴
# menu = ["점전하 & 쿨롱의 법칙", "전속밀도 & 가우스 법칙", "전위 & 에너지", "무한 선전하/평면전하", "정전 용량 계산"]
# choice = st.sidebar.selectbox("📂 분석 항목 선택", menu)
# 
# # --- 1. 점전하 & 쿨롱의 법칙 ---
# if choice == "점전하 & 쿨롱의 법칙":
#     st.header("점전하와 쿨롱의 법칙")
#     col1, col2 = st.columns([1, 1])
# 
#     with col1:
#         st.subheader("🔢 실시간 계산기")
#         q1 = st.number_input("전하 1 (Q1) [C]", value=1e-6, format="%.2e")
#         q2 = st.number_input("전하 2 (Q2) [C]", value=2e-6, format="%.2e")
#         r = st.slider("거리 (R) [m]", 0.1, 10.0, 1.0)
# 
#         force = (1 / (4 * np.pi * EPS_0)) * (q1 * q2 / r**2)
#         st.success(f"**계산된 정전기력 (F):** {force:.4e} [N]")
#         st.latex(r"F = \frac{1}{4\pi\epsilon_0} \frac{Q_1 Q_2}{R^2}")
# 
#     with col2:
#         st.subheader("📊 거리-힘 그래프")
#         dist = np.linspace(0.1, 5, 100)
#         f_vals = (1 / (4 * np.pi * EPS_0)) * (q1 * q2 / dist**2)
#         fig, ax = plt.subplots()
#         ax.plot(dist, f_vals, color='red', lw=2)
#         ax.axvline(r, color='blue', linestyle='--', label=f'Current R={r}m')
#         ax.set_xlabel("Distance [m]"); ax.set_ylabel("Force [N]")
#         ax.legend(); st.pyplot(fig)
# 
# # --- 2. 전속밀도 & 가우스 법칙 ---
# elif choice == "전속밀도 & 가우스 법칙":
#     st.header("전속밀도 (D)와 가우스 법칙")
#     col1, col2 = st.columns([1, 1])
# 
#     with col1:
#         st.subheader("🔢 실시간 계산기")
#         Q = st.number_input("중심 전하량 (Q) [C]", value=1e-9, format="%.2e")
#         r_d = st.slider("측정 지점 거리 (r) [m]", 0.1, 5.0, 1.0)
# 
#         D = Q / (4 * np.pi * r_d**2)
#         E = D / EPS_0
#         st.metric("전속밀도 (D)", f"{D:.4e} [C/m²]")
#         st.metric("전계의 세기 (E)", f"{E:.4e} [V/m]")
#         st.latex(r"D = \epsilon_0 E = \frac{Q}{4\pi r^2}")
# 
#     with col2:
#         st.subheader("📊 전계 벡터장 시각화")
#         x, y = np.meshgrid(np.linspace(-2,2,10), np.linspace(-2,2,10))
#         u, v = x/(x**2+y**2)**1.5, y/(x**2+y**2)**1.5
#         fig, ax = plt.subplots()
#         ax.quiver(x, y, u, v, color='purple')
#         ax.plot(0,0,'ro', markersize=10)
#         ax.set_title("Electric Flux Density Direction")
#         st.pyplot(fig)
# 
# # --- 3. 전위 & 에너지 ---
# elif choice == "전위 & 에너지":
#     st.header("전위 (V) 및 정전 에너지 (W)")
#     col1, col2 = st.columns([1, 1])
# 
#     with col1:
#         st.subheader("🔢 실시간 계산기")
#         q_v = st.number_input("전하량 (Q) [C]", value=1e-9, format="%.2e")
#         r_v = st.slider("거리 (r) [m]", 0.1, 10.0, 1.0)
# 
#         V = q_v / (4 * np.pi * EPS_0 * r_v)
#         st.success(f"**해당 지점의 전위 (V):** {V:.4f} [V]")
#         st.latex(r"V = \frac{Q}{4\pi\epsilon_0 r}")
# 
#     with col2:
#         st.subheader("📊 전위 감쇠 곡선")
#         rs = np.linspace(0.1, 10, 100)
#         vs = q_v / (4 * np.pi * EPS_0 * rs)
#         fig, ax = plt.subplots()
#         ax.plot(rs, vs, color='green')
#         ax.set_xlabel("Distance [m]"); ax.set_ylabel("Potential [V]")
#         st.pyplot(fig)
# 
# # --- 4. 무한 선전하/평면전하 (추가항목) ---
# elif choice == "무한 선전하/평면전하":
#     st.header("특수 전하 분포에 따른 전계")
#     type_sel = st.radio("전하 형태 선택", ["무한 선전하 (Line)", "무한 평면전하 (Sheet)"])
# 
#     col1, col2 = st.columns([1, 1])
#     with col1:
#         if type_sel == "무한 선전하 (Line)":
#             rho_l = st.number_input("선전하 밀도 (ρL) [C/m]", value=1e-9, format="%.2e")
#             r_l = st.slider("수직 거리 (ρ) [m]", 0.1, 5.0, 1.0)
#             E_l = rho_l / (2 * np.pi * EPS_0 * r_l)
#             st.latex(r"E = \frac{\rho_L}{2\pi\epsilon_0 \rho}")
#             st.info(f"계산된 전계: {E_l:.4e} [V/m]")
#         else:
#             rho_s = st.number_input("면전하 밀도 (ρS) [C/m²]", value=1e-9, format="%.2e")
#             E_s = rho_s / (2 * EPS_0)
#             st.latex(r"E = \frac{\rho_S}{2\epsilon_0}")
#             st.info(f"계산된 전계: {E_s:.4e} [V/m] (거리에 무관)")
# 
#     with col2:
#         st.subheader("💡 특징")
#         if type_sel == "무한 선전하 (Line)":
#             st.write("전계가 거리 r에 반비례하여 감소합니다.")
#         else:
#             st.write("무한 평면의 경우, 전계는 거리와 상관없이 일정합니다!")
# 
# # --- 5. 정전 용량 계산 ---
# elif choice == "정전 용량 계산":
#     st.header("평행판 커패시터 계산")
#     col1, col2 = st.columns([1, 1])
# 
#     with col1:
#         area = st.number_input("판의 면적 (S) [m²]", value=0.01)
#         dist_c = st.number_input("판 사이 간격 (d) [m]", value=0.001)
#         eps_r = st.number_input("비유전율 (εr)", value=1.0)
# 
#         C = (eps_r * EPS_0 * area) / dist_c
#         st.metric("정전 용량 (C)", f"{C:.4e} [F]")
#         st.latex(r"C = \epsilon_r \epsilon_0 \frac{S}{d}")
# 
#     with col2:
#         volt = st.slider("인가 전압 (V)", 0, 100, 10)
#         energy = 0.5 * C * (volt**2)
#         st.metric("축적된 에너지 (W)", f"{energy:.4e} [J]")
#         st.latex(r"W = \frac{1}{2}CV^2")

"""# 새 섹션

# 새 섹션
"""

import urllib
print("Password (IP Address):", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())
get_ipython().system_raw('streamlit run app.py &')
!npx localtunnel --port 8501